export const AUTHORIZING_USER = 'AUTHORIZING_USER';
export const AUTHORIZING_SUCCESS = 'AUTHORIZING_SUCCESS';
export const AUTHORIZING_FAIL = 'AUTHORIZING_FAIL';


export const LOG_USER_IN = 'LOG_USER_IN';
export const LOG_USER_SUCCESS = 'LOG_USER_SUCCESS';
export const LOG_USER_FAIL = 'LOG_USER_FAIL';


export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOG_USER_OUT = 'LOG_USER_OUT';

export const ADD_POLL = 'ADD_POLL';
export const ADD_POLL_SUCCESS = 'ADD_POLL_SUCCESS';
export const ADD_POLL_FAIL = 'ADD_POLL_FAIL';

export const ADD_POLL_TOPIC = 'ADD_POLL_TOPIC';
export const ADD_POLL_TOPIC_SUCCESS = 'ADD_POLL_TOPIC_SUCCESS';
export const ADD_POLL_TOPIC_FAIL = 'ADD_POLL_TOPIC_FAIL';
